# Changes here will be overwritten by Copier
AnswerStrategy: recommended
AuthorEmail: abel.s.siqueira@gmail.com
AuthorName: Abel Soares Siqueira
Indentation: 2
JuliaMinVersion: '1.6'
License: MIT
PackageName: BestieRecommended
PackageOwner: abelsiqueira
PackageUUID: 49999571-eea7-54eb-9328-55f56e583ba6
_commit: v0.7.1
_src_path: https://github.com/abelsiqueira/BestieTemplate.jl
