name: "Usage question"
description: Questions related to the usage
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this question!

        Please, before submitting, make sure that:

        - You have checked the [documentation](https://abelsiqueira.github.io/BestieRecommended.jl) and haven't found enough information
        - There is not an [existing issue](https://github.com/abelsiqueira/BestieRecommended.jl/issues) with the same question
        - You have read the [contributing guide](https://abelsiqueira.github.io/BestieRecommended.jl/dev/90-contributing/)
        - You are following the [code of conduct](https://github.com/abelsiqueira/BestieRecommended.jl/blob/main/CODE_OF_CONDUCT.md)

        The form below should help you in filling out this issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write your question
    validations:
      required: true
